import type { Car } from '@/core/types';

export const cars: Car[] = [
  {
    id: 'camry-xse',
    marca: 'Toyota',
    modelo: 'Camry XSE',
    anio: 2024,
    precio: 680000,
    tipoCombustible: 'Gasoline',
    transmision: 'Automatic',
    motor: '2.5L 4-Cilindros',
    caracteristicas: ['Techo solar panorámico', 'Toyota Safety Sense 2.5+', 'Pantalla táctil de 9 pulgadas', 'Asientos de piel SofTex'],
    imagenUrl: 'https://images.unsplash.com/photo-1729080562616-3b9758cae13e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxzZWRhbiUyMHJvam98ZW58MHx8fHwxNzYzMDgyOTA1fDA&ixlib=rb-4.1.0&q=80&w=1080',
    tipo: 'Sedan',
    cilindrosMotor: 4,
    color: 'Rojo',
    pasajeros: 5,
  },
  {
    id: 'f150-lariat',
    marca: 'Ford',
    modelo: 'F-150 Lariat',
    anio: 2024,
    precio: 1350000,
    tipoCombustible: 'Hybrid',
    transmision: 'Automatic',
    motor: '3.5L PowerBoost V6 Híbrido',
    caracteristicas: ['Pro Power Onboard', 'Pantalla SYNC 4 de 12 pulgadas', 'Interior de cuero', 'Co-Pilot360 Assist 2.0'],
    imagenUrl: 'https://images.unsplash.com/photo-1681351623077-e4cc438f0548?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxjYW1pb25ldGElMjBhenVsfGVufDB8fHx8MTc2MzA4MjkwNXww&ixlib=rb-4.1.0&q=80&w=1080',
    tipo: 'Truck',
    cilindrosMotor: 6,
    color: 'Azul',
    pasajeros: 5,
  },
  {
    id: 'model-3-lr',
    marca: 'Tesla',
    modelo: 'Model 3 Long Range',
    anio: 2024,
    precio: 980000,
    tipoCombustible: 'Electric',
    transmision: 'Automatic',
    motor: 'Dual Motor',
    caracteristicas: ['Piloto automático', 'Pantalla táctil de 15 pulgadas', 'Techo de cristal', 'Aceleración de 0 a 100 km/h en 4.4s'],
    imagenUrl: 'https://images.unsplash.com/photo-1643475246169-dd57253b646a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHx0ZXNsYSUyMGJsYW5jb3xlbnwwfHx8fDE3NjMwODI5MDV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    tipo: 'Sedan',
    cilindrosMotor: 0,
    color: 'Blanco',
    pasajeros: 5,
  },
  {
    id: 'crv-touring',
    marca: 'Honda',
    modelo: 'CR-V Touring',
    anio: 2024,
    precio: 850000,
    tipoCombustible: 'Hybrid',
    transmision: 'Automatic',
    motor: '2.0L Híbrido',
    caracteristicas: ['Tracción en las 4 ruedas (AWD)', 'Honda Sensing', 'Sistema de audio Bose', 'Cargador inalámbrico'],
    imagenUrl: 'https://images.unsplash.com/photo-1733759845506-e197dbc047c8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHxzdXYlMjBncmlzfGVufDB8fHx8MTc2MzA4MjkwNXww&ixlib=rb-4.1.0&q=80&w=1080',
    tipo: 'SUV',
    cilindrosMotor: 4,
    color: 'Gris',
    pasajeros: 5,
  },
  {
    id: '911-gt3',
    marca: 'Porsche',
    modelo: '911 GT3',
    anio: 2024,
    precio: 3800000,
    tipoCombustible: 'Gasoline',
    transmision: 'Automatic',
    motor: '4.0L 6-Cilindros Boxer',
    caracteristicas: ['Paquete Clubsport', 'Frenos cerámicos (PCCB)', 'Eje trasero direccional', 'Aerodinámica activa'],
    imagenUrl: 'https://images.unsplash.com/photo-1711998034162-380d2c7a5875?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxwb3JzY2hlJTIwYW1hcmlsbG98ZW58MHx8fHwxNzYzMDgyOTA1fDA&ixlib=rb-4.1.0&q=80&w=1080',
    tipo: 'Sports',
    cilindrosMotor: 6,
    color: 'Amarillo',
    pasajeros: 2,
  },
  {
    id: 'ioniq5-limited',
    marca: 'Hyundai',
    modelo: 'Ioniq 5 Limited',
    anio: 2024,
    precio: 1100000,
    tipoCombustible: 'Electric',
    transmision: 'Automatic',
    motor: 'Motor Eléctrico',
    caracteristicas: ['Carga ultra rápida (800V)', 'Asientos de gravedad cero', 'Head-Up Display con AR', 'Diseño retrofuturista'],
    imagenUrl: 'https://picsum.photos/seed/ioniq5-limited/800/600',
    tipo: 'SUV',
    cilindrosMotor: 0,
    color: 'Plata',
    pasajeros: 5,
  },
  {
    id: 'wrangler-rubicon',
    marca: 'Jeep',
    modelo: 'Wrangler Rubicon',
    anio: 2024,
    precio: 1250000,
    tipoCombustible: 'Gasoline',
    transmision: 'Automatic',
    motor: '3.6L V6',
    caracteristicas: ['Sistema 4x4 Rock-Trac', 'Neumáticos de 33 pulgadas', 'Puertas y techo desmontables', 'Pantalla Uconnect de 8.4 pulgadas'],
    imagenUrl: 'https://images.unsplash.com/photo-1556821043-11c39c6e69cf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxqZWVwJTIwdmVyZGV8ZW58MHx8fHwxNzYzMDgyOTA1fDA&ixlib=rb-4.1.0&q=80&w=1080',
    tipo: 'SUV',
    cilindrosMotor: 6,
    color: 'Verde',
    pasajeros: 4,
  },
  {
    id: 'bmw-330i',
    marca: 'BMW',
    modelo: '330i Sedan',
    anio: 2024,
    precio: 950000,
    tipoCombustible: 'Gasoline',
    transmision: 'Automatic',
    motor: '2.0L TwinPower Turbo',
    caracteristicas: ['BMW Curved Display', 'Parking Assistant', 'Live Cockpit Professional', 'Suspensión adaptativa M'],
    imagenUrl: 'https://images.unsplash.com/photo-1563826773-1e2b4b2cde42?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxibXclMjBuZWdyb3xlbnwwfHx8fDE3NjMwODI5MDV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    tipo: 'Sedan',
    cilindrosMotor: 4,
    color: 'Negro',
    pasajeros: 5,
  },
];
