import type { Car } from './types';

export const cars: Car[] = [
  {
    id: 'prestige-x10',
    brand: 'Prestige',
    model: 'X10',
    year: 2024,
    price: 1850000,
    mileage: 15,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    engine: '4.0L V8',
    horsepower: 550,
    features: ['Asientos de Cuero', 'Techo Solar', 'Cámara 360', 'Sistema de Sonido Premium', 'Control de Crucero Adaptativo'],
    image: 'prestige-x10',
    type: 'Sedan',
    engineCylinders: 8,
    color: 'Rojo',
    passengers: 5,
  },
  {
    id: 'aurora-gt',
    brand: 'Aurora',
    model: 'GT',
    year: 2023,
    price: 1720000,
    mileage: 18,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    engine: '2.5L 5-Cilindros Turbo',
    horsepower: 480,
    features: ['Suspensión Deportiva', 'Interior de Alcantara', 'Control de Lanzamiento', 'Detalles en Fibra de Carbono'],
    image: 'aurora-gt',
    type: 'Sports',
    engineCylinders: 5,
    color: 'Azul',
    passengers: 2,
  },
  {
    id: 'volta-ev-pro',
    brand: 'Volta',
    model: 'EV Pro',
    year: 2024,
    price: 1650000,
    mileage: 350,
    fuelType: 'Electric',
    transmission: 'Automatic',
    engine: 'Motor Dual',
    horsepower: 450,
    features: ['Piloto Automático', 'Pantalla Táctil de 17 pulgadas', 'Techo de Cristal', 'Carga Rápida', 'Filtración de Aire HEPA'],
    image: 'volta-ev-pro',
    type: 'Sedan',
    engineCylinders: 0,
    color: 'Blanco',
    passengers: 5,
  },
  {
    id: 'horizon-suv',
    brand: 'Horizon',
    model: 'Explorer',
    year: 2023,
    price: 1550000,
    mileage: 22,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    engine: '2.5L 4-Cilindros Híbrido',
    horsepower: 220,
    features: ['7 Asientos', 'Tracción Total', 'Techo Solar Panorámico', 'Apple CarPlay/Android Auto'],
    image: 'horizon-suv',
    type: 'SUV',
    engineCylinders: 4,
    color: 'Gris',
    passengers: 7,
  },
  {
    id: 'nomad-cruiser',
    brand: 'Nomad',
    model: 'Cruiser',
    year: 2024,
    price: 480000,
    mileage: 25,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    engine: '2.0L 4-Cilindros Turbo',
    horsepower: 250,
    features: ['Asientos Calefactables', 'Carga Inalámbrica', 'Monitor de Punto Ciego', 'Cabina Espaciosa'],
    image: 'nomad-cruiser',
    type: 'SUV',
    engineCylinders: 4,
    color: 'Negro',
    passengers: 5,
  },
  {
    id: 'comet-r',
    brand: 'Comet',
    model: 'R',
    year: 2023,
    price: 420000,
    mileage: 28,
    fuelType: 'Gasoline',
    transmission: 'Manual',
    engine: '1.8L Turbo',
    horsepower: 300,
    features: ['Diseño Compacto', 'Asientos Recaro', 'Frenos de Alto Rendimiento', 'Escape Deportivo'],
    image: 'comet-r',
    type: 'Hatchback',
    engineCylinders: 4,
    color: 'Amarillo',
    passengers: 4,
  },
  {
    id: 'stratus-sedan',
    brand: 'Stratus',
    model: 'Elegance',
    year: 2024,
    price: 580000,
    mileage: 45,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    engine: '2.0L Híbrido',
    horsepower: 190,
    features: ['Interior de Lujo', 'Suite de Seguridad Avanzada', 'Cabina Silenciosa', 'Iluminación Ambiental'],
    image: 'stratus-sedan',
    type: 'Sedan',
    engineCylinders: 4,
    color: 'Plata',
    passengers: 5,
  },
  {
    id: 'terra-truck',
    brand: 'Terra',
    model: 'Overland',
    year: 2023,
    price: 620000,
    mileage: 19,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    engine: '3.0L V6 Diesel',
    horsepower: 280,
    features: ['Paquete Todoterreno', 'Capacidad de Remolque', 'Revestimiento de Caja Duradero', 'Infoentretenimiento Avanzado'],
    image: 'terra-truck',
    type: 'Truck',
    engineCylinders: 6,
    color: 'Verde',
    passengers: 5,
  },
];
