import type { Car } from './types';

export const cars: Car[] = [
  {
    id: 'prestige-x10',
    brand: 'Prestige',
    model: 'X10',
    year: 2024,
    price: 85000,
    mileage: 15,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    engine: '4.0L V8',
    horsepower: 550,
    features: ['Leather Seats', 'Sunroof', '360 Camera', 'Premium Sound System', 'Adaptive Cruise Control'],
    image: 'prestige-x10',
  },
  {
    id: 'aurora-gt',
    brand: 'Aurora',
    model: 'GT',
    year: 2023,
    price: 72000,
    mileage: 18,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    engine: '3.5L V6 Twin-Turbo',
    horsepower: 480,
    features: ['Sport-tuned Suspension', 'Alcantara Interior', 'Launch Control', 'Carbon Fiber Trim'],
    image: 'aurora-gt',
  },
  {
    id: 'volta-ev-pro',
    brand: 'Volta',
    model: 'EV Pro',
    year: 2024,
    price: 65000,
    mileage: 350,
    fuelType: 'Electric',
    transmission: 'Automatic',
    engine: 'Dual Motor',
    horsepower: 450,
    features: ['Autopilot', '17-inch Touchscreen', 'Glass Roof', 'Fast Charging', 'HEPA Air Filtration'],
    image: 'volta-ev-pro',
  },
  {
    id: 'horizon-suv',
    brand: 'Horizon',
    model: 'Explorer',
    year: 2023,
    price: 55000,
    mileage: 22,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    engine: '2.5L 4-Cylinder Hybrid',
    horsepower: 220,
    features: ['7-Seater', 'All-Wheel Drive', 'Panoramic Sunroof', 'Apple CarPlay/Android Auto'],
    image: 'horizon-suv',
  },
  {
    id: 'nomad-cruiser',
    brand: 'Nomad',
    model: 'Cruiser',
    year: 2024,
    price: 48000,
    mileage: 25,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    engine: '2.0L 4-Cylinder Turbo',
    horsepower: 250,
    features: ['Heated Seats', 'Wireless Charging', 'Blind Spot Monitor', 'Spacious Cabin'],
    image: 'nomad-cruiser',
  },
  {
    id: 'comet-r',
    brand: 'Comet',
    model: 'R',
    year: 2023,
    price: 42000,
    mileage: 28,
    fuelType: 'Gasoline',
    transmission: 'Manual',
    engine: '1.8L Turbo',
    horsepower: 300,
    features: ['Compact Design', 'Recaro Seats', 'Performance Brakes', 'Sport Exhaust'],
    image: 'comet-r',
  },
  {
    id: 'stratus-sedan',
    brand: 'Stratus',
    model: 'Elegance',
    year: 2024,
    price: 58000,
    mileage: 45,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    engine: '2.0L Hybrid',
    horsepower: 190,
    features: ['Luxury Interior', 'Advanced Safety Suite', 'Quiet Cabin', 'Ambient Lighting'],
    image: 'stratus-sedan',
  },
  {
    id: 'terra-truck',
    brand: 'Terra',
    model: 'Overland',
    year: 2023,
    price: 62000,
    mileage: 19,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    engine: '3.0L V6 Diesel',
    horsepower: 280,
    features: ['Off-road Package', 'Towing Capacity', 'Durable Bedliner', 'Advanced Infotainment'],
    image: 'terra-truck',
  },
];
